notes/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    # Examples:
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^(\d+)/$', 'notes.views.view_notes', name='view_notes'),
    url(r'^(\d+)/add$', 'notes.views.add_sermon', name='add_sermon'),
    url(r'^new$', 'notes.views.new_sermon', name='new_sermon'),
)

sermonbuddy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'notes.views.home_page', name='home'),
    url(r'^notes/', include('notes.urls')),
)

notes/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Series(models.Model):
	
	def get_absolute_url(self):
		return reverse('view_notes', args=[self.id])

class Sermon(models.Model):
    title = models.CharField(max_length=100)
    speaker = models.CharField(max_length=100, default='', null=True, blank=True)
    text = models.TextField(default='')
    date = models.DateTimeField(auto_now_add=True)
    series = models.ForeignKey(Series, default=None)

    class Meta:
    	ordering = ['-date']

notes/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from notes.models import Sermon, Series

# Create your views here.
def home_page(request):
    return render(request, 'notes/home.html')

def new_sermon(request):
    if request.method == 'POST':
        series = Series.objects.create()
        sermon = Sermon(
            title=request.POST['title'], 
            speaker=request.POST['speaker'], 
            text=request.POST['notes'],
            series=series,
        )
        try:
            sermon.full_clean()
            sermon.save()
        except ValidationError:
            series.delete()
            error = "You can't have an empty sermon title"
            return render(request, 'notes/new_sermon.html', {'error': error, 'series': series})
        return redirect(series)
    return render(request, 'notes/new_sermon.html')

def view_notes(request, series_id):
    series = Series.objects.get(id=series_id)
    return render(request, 'notes/list.html', {'series': series})

def add_sermon(request, series_id):
    series = Series.objects.get(id=series_id)
    if request.method == 'POST':
        added_sermon = Sermon(
                title=request.POST['title'], 
                speaker=request.POST['speaker'], 
                text=request.POST['notes'],
                series=series,
            )
        try:
            added_sermon.full_clean()
            added_sermon.save()
        except ValidationError:
            error = "You can't have an empty sermon title"
            return render(request, 'notes/add_sermon.html', {'error': error, 'series': series})
        return redirect(series)
    return render(request, 'notes/add_sermon.html', {'series': series})

notes/templates/notes/add_sermon.html
{% extends 'notes/base_form.html' %}

{% block header_text %} Add a New Sermon {% endblock %}

{% block form_action %} {% url 'add_sermon' series.id %} {% endblock %}

notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<title> SermonBuddy - Sermon Notes Application </title>

		<!-- Bootstrap -->
    	<link href="/static/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">

	</head>
    <body>
    <div class="container">

    	<div class="row">
	        <div class="col-md-6 col-md-offset-3">
		    	<div class="text-center">
		    		<div class="page-header">
			        	<h1>{% block header_text %}{% endblock %}</h1>
			        </div>
			        {% block content %} {% endblock %}
			    </div>
		    </div>
		</div>

		<div class="row">
	        <div class="col-md-6 col-md-offset-3">
	            {% block table %}
	            {% endblock %}
	        </div>
		</div>
	

	</div>
    </body>
</html>

notes/templates/notes/base_form.html
{% extends 'notes/base.html' %}

{% block header_text %} Add a New Sermon {% endblock %}

{% block content %} 

<form action="{% block form_action %}{% endblock %}" method="post" role="form">
  <div class="form-group">
  	<label for="id_sermon_title"> Sermon Title </label>
	<input type="text" name="title" id="id_sermon_title" placeholder="Enter a Sermon Title" />
  </div>

  {% if error %}
    <div class="form-group has-error">
    <span class="help-block">{{ error }}</span>
  </div>
  {% endif %}
  <div class="form-group">
    <label for="id_sermon_speaker"> Sermon Speaker </label>
	<input type="text" name= "speaker" id="id_sermon_speaker" placeholder="The Speaker" /> 
  </div>
  <div class="form-group">
  	<label for="id_sermon_speaker"> Sermon Notes </label>
  	<div class="row">
  	<div class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4">
	<textarea rows="3" class="form-control" name="notes" 
            placeholder="Write your Notes Here" id="id_sermon_notes"> 
	</textarea>
	</div>
	</div>
  </div>
	<button type="submit" class="btn btn-default" id="id_sermon_submit">Save</button>
	{% csrf_token %}
</form>

{% endblock %}

notes/templates/notes/home.html
{% extends 'notes/base.html' %}

{% block header_text %}Sermon Buddy <small>Sermon Notes Application</small> {% endblock %}
{% block content %}
<div class="jumbotron">
<p class="lead">
Sermon Buddy is the only online platform for saving your sermon notes.<br/>
Keep track of all your sermon notes on one convenient platform. Get started now.
</p>
    <p>
       <a class="btn btn-lg btn-info" role="button" href={% url 'new_sermon' %} id="new_sermon"> Add a New Sermon</a>
    </p>
</div>
{% endblock %}

notes/templates/notes/list.html
{% extends 'notes/base.html' %}

{% block header_text %} Your Sermon Notes {% endblock %}

{% block table %}
    <table id="id_list_table" class="table table-hover">
        {% for item in series.sermon_set.all %}
            <tr><td>Date Added: {{ item.date}} </td></tr>
            <tr><td>{{ item.title }}</td></tr>
             <tr><td>{{ item.speaker }}</td></tr>
             <tr><td>{{ item.text }}</td></tr>
             <tr><td> <br/> </td></tr>
            {% endfor %}
    </table>
{% endblock %}

{% block content %}
        <p>
         <a class="btn btn-lg btn-info" role="button" href={% url 'add_sermon' series.id %} id="add_sermon">
         <span class="glyphicon glyphicon-plus"></span>
            Add a New Sermon to this Series </a>
        </p>
{% endblock %}

notes/templates/notes/new_sermon.html
{% extends 'notes/base_form.html' %}

{% block form_action %} {% url 'new_sermon' %} {% endblock %}